# Generated by Django 5.1.2 on 2024-10-28 10:25

import audio.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audios/', validators=[audio.models.validate_audio_format])),
                ('file_format', models.CharField(blank=True, choices=[('mp3', 'MP3'), ('wav', 'WAV'), ('m4a', 'M4A')], max_length=3, null=True)),
                ('language', models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Rus'), ('en', 'Ingliz'), ('kq', 'Qoraqalpoq')], max_length=2)),
                ('transcription', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('processing_status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audio.category')),
            ],
        ),
    ]
