# Generated by Django 5.1.2 on 2024-10-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='file',
        ),
        migrations.AddField(
            model_name='audiofile',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='language',
            field=models.CharField(choices=[('uz', 'O‘zbek'), ('ru', 'Rus'), ('en', 'Ingliz'), ('kq', 'Qoraqalpoq')], max_length=2),
        ),
    ]
