# Generated by Django 5.1.2 on 2024-10-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_alter_audiofile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
