# Generated by Django 5.1.2 on 2024-10-23 05:50

import audio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_alter_audiofile_audio_file_alter_audiofile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='file_format',
            field=models.CharField(blank=True, choices=[('mp3', 'MP3'), ('wav', 'WAV'), ('m4a', 'M4A')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audios/', validators=[audio.models.validate_audio_format]),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='language',
            field=models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Rus'), ('en', 'Ingliz'), ('kq', 'Qoraqalpoq')], max_length=2),
        ),
    ]
