# Generated by Django 5.1.2 on 2024-10-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_audiofile_file_format_audiofile_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='processing_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
